### ISSUE TITLE
8 bit hex files

### ISSUE THREAD

**Issue by jneilliii** [frealmyr/marlin-build#15]
First thank you for this great docker image. I think it's an awesome idea for using github actions to keep firmware updated whenever you want. One thing I ran into is that I'm one of the old timers with an 8 bit board still and my mega2560 based firmware compiles into a hex file, not bin. Therefore, when the process gets to where it checks the md5, etc. it fails because the file is not there. Would be great to have an env variable for bin vs hex or something similar or am I missing an existing option?

**Comment by frealmyr** [comment]
> First thank you for this great docker image. I think it's an awesome idea for using github actions to keep firmware updated whenever you want. One thing I ran into is that I'm one of the old timers with an 8 bit board still and my mega2560 based firmware compiles into a hex file, not bin. Therefore, when the process gets to where it checks the md5, etc. it fails because the file is not there. Would be great to have an env variable for bin vs hex or something similar or am I missing an existing option?

The script is hard coded for `.bin` files, but adding a override variable seems like a good solution for solving this.

I considered adding logic for finding out the firmware file extension, but that would invite some headaches inside the build folder. 🤔
