### ISSUE TITLE
Failure to upload build for new board

### ISSUE THREAD

**Issue by xcasxcursex** [frealmyr/marlin-build#7]
First off, thanks for this, it's really showing off the power of the tools you've used in an elegant way!

I'm fork #1 so I was bound to find some small issue ;) My build failed to push to the repo the first time out, giving me the error:

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	Firmware/Builds/STM32F103RET6_creality/

nothing added to commit but untracked files present (use "git add" to track)
Error: Process completed with exit code 1.
```
https://github.com/xcasxcursex/Ender3v2Marlin/runs/1503176605?check_suite_focus=true

A quick search led me to simply add a line to the push job:

` git add .`
https://github.com/xcasxcursex/Ender3v2Marlin/commit/a7f7a2cbc5e2221ba18353286b95a4db7e94cdff

This seems to have fixed things but I'm not proficient enough to know if this is the 'right' way to fix it, so instead of a PR, I've filed this issue.

**Comment by frealmyr** [comment]
Right, this is because i used `git commit -am "Compiled firmware"`

This will only add changes made to tracked files, and not add new files to the commit. Adding `git add .` before this step as you figured out, will also add any new files to the commit.

You want to create a quick PR for the github action example? 😊

**Comment by xcasxcursex** [comment]
> You want to create a quick PR for the github action example? 😊

First time, am I doing it right? :D

**Comment by frealmyr** [comment]
> > You want to create a quick PR for the github action example? 😊
> 
> First time, am I doing it right? :D

Looks good, merged the PR 👍🏻
